import React from 'react';
import { Footer } from '../components';
import Aboutus from '../components/Aboutus';
import { useStateContext } from '../context/StateContext';
import Head from 'next/head';
const About = () => {
  const { cat } = useStateContext();

  return (
    <div>
      <Head>
        <title>About Tejdharart</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/logo_tejdharart.jpg' />
      </Head>
      <Aboutus />
      <Footer data={cat} />
    </div>
  );
};

export default About;
