import React from 'react';
import { Footer } from '../components';
import Head from 'next/head';
import AboutFounder from '../components/AboutFounder';
import { useStateContext } from '../context/StateContext';
const Founder = () => {
  const { cat } = useStateContext();
  return (
    <div>
      <Head>
        <title>Founder | Tejdharart</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/logo_tejdharart.jpg' />
      </Head>
      <AboutFounder />
      <Footer data={cat} />
    </div>
  );
};

export default Founder;
